@baseUrl = http://localhost:3000/api/v1
@leadUUID = leadUUIDexample
@userUUID = userUUIDexample
@authToken = Bearer authToken

// =====================================
// App
// =====================================
# @name Hello
GET {{baseUrl}}/
###

// =====================================
// Leads
// =====================================
# @name CreateLead
POST {{baseUrl}}/leads
Content-Type: application/json

{
    "name": "Manuel",
    "email": "manuel@teste.com",
    "type": "resident",
    "phone_number": "(00) 0 0000-0000"
}
###

# @name GetLeads
GET {{baseUrl}}/leads
Authorization: {{authToken}}
###

# @name GetLeadById
GET {{baseUrl}}/leads/leadUUID
Authorization: {{authToken}}
###

# @name UpdateLeadById
PATCH {{baseUrl}}/leads/{{leadUUID}}
Authorization: {{authToken}}
Content-Type: application/json

{
    "name": "Teste"
}
###

# @name DeleteLeadById
DELETE {{baseUrl}}/leads/{{leadUUID}}
Authorization: {{authToken}}
Content-Type: application/json
###

// =====================================
// Auth
// =====================================
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email": "admin@teste.com",
    "password": "12345678"
}
###

# @name register
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name": "Administrador",
    "username": "admin-user",
    "birth_date": "01/05/2004",
    "email": "admin@teste.com",
    "phone_number": "+558999999999",
    "role": "superuser",
    "password": "12345678",
    "password_confirm": "12345678"
}
###


// =====================================
// Users
// =====================================
# @name GetUsers
GET {{baseUrl}}/users
Authorization: {{authToken}}
###

# @name GetIsUsernameAvailable
GET {{baseUrl}}/users/username-available?username=admin-sudo
###

# @name GetMe
GET {{baseUrl}}/users/me
Authorization: {{authToken}}
###

# @name GetUserById
GET {{baseUrl}}/users/{{userUUID}}
Authorization: {{authToken}}
###

# @name UpdateUserById
PATCH {{baseUrl}}/users/{{userUUID}}
Authorization: {{authToken}}
Content-Type: application/json

{
    "name": "Teste"
}
###

# @name DeleteUserById
DELETE {{baseUrl}}/users/{{userUUID}}
Authorization: {{authToken}}
Content-Type: application/json
###

// =====================================
// Cities
// =====================================
# @name GetCities
GET {{baseUrl}}/cities
Authorization: {{authToken}}
###

# @name GetCityById
GET {{baseUrl}}/cities/dd28534d-8a43-47c1-beca-896763616403
Authorization: {{authToken}}
###

# @name GetCityMedia
GET {{baseUrl}}/cities/3f9fc94a-143c-4ed9-a45f-bd21b88d315b
Authorization: {{authToken}}
###

// =====================================
// Companies
// =====================================
# @name GetCompanies
GET {{baseUrl}}/companies
Authorization: {{authToken}}
###

# @name GetCompanyById
GET {{baseUrl}}/companies/dd28534d-8a43-47c1-beca-896763616403
Authorization: {{authToken}}
###

# @name GetCompanyMedia
GET {{baseUrl}}/companies/3f9fc94a-143c-4ed9-a45f-bd21b88d315b/media
Authorization: {{authToken}}
###